const settingsExceptionSubscriptions = 
[
    {
      "CustId": "975820",
      "Description": "Veh is restrict from purch this day of week",
      "ExceptionSubscriptionId": "361114",
      "HostXref": null,
      "Type": "S",
      "active_flag": "true",
      "create_date": "0001-01-01T00:00:00",
      "create_user": null,
      "delivery_destination1": "HMARKS@DIVERSIFIEDSYS.COM",
      "delivery_destination2": null,
      "delivery_method1": "E",
      "delivery_method2": "E",
      "exception_code": "108301",
      "update_date": "2021-12-27T12:15:14",
      "update_user": null
    },
    {
      "CustId": "975820",
      "Description": "Fuel volume exceeds vehicles tank capacity",
      "ExceptionSubscriptionId": "0",
      "HostXref": null,
      "Type": "S",
      "active_flag": "false",
      "create_date": "0001-01-01T00:00:00",
      "create_user": null,
      "delivery_destination1": "HMARKS@DIVERSIFIEDSYS.COM",
      "delivery_destination2": null,
      "delivery_method1": "E",
      "delivery_method2": "E",
      "exception_code": "108004",
      "update_date": "2022-03-07T08:09:31",
      "update_user": null
    },
    {
      "CustId": "975820",
      "Description": "Emp is restricted from purchases at site",
      "ExceptionSubscriptionId": "0",
      "HostXref": null,
      "Type": "N",
      "active_flag": "false",
      "create_date": "0001-01-01T00:00:00",
      "create_user": null,
      "delivery_destination1": "HMARKS@DIVERSIFIEDSYS.COM",
      "delivery_destination2": null,
      "delivery_method1": "E",
      "delivery_method2": "E",
      "exception_code": "108207",
      "update_date": "2022-03-07T08:09:31",
      "update_user": null
    },
    {
      "CustId": "975820",
      "Description": "Vehicle has exceeded its cycle fuel limit",
      "ExceptionSubscriptionId": "0",
      "HostXref": null,
      "Type": "S",
      "active_flag": "false",
      "create_date": "0001-01-01T00:00:00",
      "create_user": null,
      "delivery_destination1": "HMARKS@DIVERSIFIEDSYS.COM",
      "delivery_destination2": null,
      "delivery_method1": "E",
      "delivery_method2": "E",
      "exception_code": "108005",
      "update_date": "2022-03-07T08:09:31",
      "update_user": null
    },
    {
      "CustId": "975820",
      "Description": "Veh has exceeded its Fleet Supplies limit",
      "ExceptionSubscriptionId": "0",
      "HostXref": null,
      "Type": "S",
      "active_flag": "false",
      "create_date": "0001-01-01T00:00:00",
      "create_user": null,
      "delivery_destination1": "HMARKS@DIVERSIFIEDSYS.COM",
      "delivery_destination2": null,
      "delivery_method1": "E",
      "delivery_method2": "E",
      "exception_code": "108007",
      "update_date": "2022-03-07T08:09:31",
      "update_user": null
    },
    {
      "CustId": "975820",
      "Description": "Veh is restricted from purchases at site",
      "ExceptionSubscriptionId": "0",
      "HostXref": null,
      "Type": "N",
      "active_flag": "false",
      "create_date": "0001-01-01T00:00:00",
      "create_user": null,
      "delivery_destination1": "HMARKS@DIVERSIFIEDSYS.COM",
      "delivery_destination2": null,
      "delivery_method1": "E",
      "delivery_method2": "E",
      "exception_code": "108107",
      "update_date": "2022-03-07T08:09:31",
      "update_user": null
    },
    {
      "CustId": "975820",
      "Description": "Veh is restrict from purch this time of day",
      "ExceptionSubscriptionId": "0",
      "HostXref": null,
      "Type": "S",
      "active_flag": "false",
      "create_date": "0001-01-01T00:00:00",
      "create_user": null,
      "delivery_destination1": "HMARKS@DIVERSIFIEDSYS.COM",
      "delivery_destination2": null,
      "delivery_method1": "E",
      "delivery_method2": "E",
      "exception_code": "108302",
      "update_date": "2022-03-07T08:09:31",
      "update_user": null
    },
    {
      "CustId": "975820",
      "Description": "Manually keyed transactions at site",
      "ExceptionSubscriptionId": "0",
      "HostXref": null,
      "Type": "N",
      "active_flag": "false",
      "create_date": "0001-01-01T00:00:00",
      "create_user": null,
      "delivery_destination1": "HMARKS@DIVERSIFIEDSYS.COM",
      "delivery_destination2": null,
      "delivery_method1": "E",
      "delivery_method2": "E",
      "exception_code": "100275",
      "update_date": "2022-03-07T08:09:31",
      "update_user": null
    },
    {
      "CustId": "975820",
      "Description": "This vehicle is locked",
      "ExceptionSubscriptionId": "0",
      "HostXref": null,
      "Type": "S",
      "active_flag": "false",
      "create_date": "0001-01-01T00:00:00",
      "create_user": null,
      "delivery_destination1": "HMARKS@DIVERSIFIEDSYS.COM",
      "delivery_destination2": null,
      "delivery_method1": "E",
      "delivery_method2": "E",
      "exception_code": "108506",
      "update_date": "2022-03-07T08:09:31",
      "update_user": null
    },
    {
      "CustId": "975820",
      "Description": "This employee is locked",
      "ExceptionSubscriptionId": "0",
      "HostXref": null,
      "Type": "S",
      "active_flag": "false",
      "create_date": "0001-01-01T00:00:00",
      "create_user": null,
      "delivery_destination1": "HMARKS@DIVERSIFIEDSYS.COM",
      "delivery_destination2": null,
      "delivery_method1": "E",
      "delivery_method2": "E",
      "exception_code": "108515",
      "update_date": "2022-03-07T08:09:31",
      "update_user": null
    },
    {
      "CustId": "975820",
      "Description": "Veh is restricted from purchasing this fuel",
      "ExceptionSubscriptionId": "0",
      "HostXref": null,
      "Type": "S",
      "active_flag": "false",
      "create_date": "0001-01-01T00:00:00",
      "create_user": null,
      "delivery_destination1": "HMARKS@DIVERSIFIEDSYS.COM",
      "delivery_destination2": null,
      "delivery_method1": "E",
      "delivery_method2": "E",
      "exception_code": "108003",
      "update_date": "2022-03-07T08:09:31",
      "update_user": null
    },
    {
      "CustId": "975820",
      "Description": "Veh has exceeded its daily transaction limit",
      "ExceptionSubscriptionId": "0",
      "HostXref": null,
      "Type": "S",
      "active_flag": "false",
      "create_date": "0001-01-01T00:00:00",
      "create_user": null,
      "delivery_destination1": "HMARKS@DIVERSIFIEDSYS.COM",
      "delivery_destination2": null,
      "delivery_method1": "E",
      "delivery_method2": "E",
      "exception_code": "108010",
      "update_date": "2022-03-07T08:09:31",
      "update_user": null
    },
    {
      "CustId": "975820",
      "Description": "Emp not auth for purch with this dept veh",
      "ExceptionSubscriptionId": "0",
      "HostXref": null,
      "Type": "S",
      "active_flag": "false",
      "create_date": "0001-01-01T00:00:00",
      "create_user": null,
      "delivery_destination1": "HMARKS@DIVERSIFIEDSYS.COM",
      "delivery_destination2": null,
      "delivery_method1": "E",
      "delivery_method2": "E",
      "exception_code": "108402",
      "update_date": "2022-03-07T08:09:31",
      "update_user": null
    },
    {
      "CustId": "975820",
      "Description": "Vehicle has exceeded expected range",
      "ExceptionSubscriptionId": "0",
      "HostXref": null,
      "Type": "N",
      "active_flag": "false",
      "create_date": "0001-01-01T00:00:00",
      "create_user": null,
      "delivery_destination1": "HMARKS@DIVERSIFIEDSYS.COM",
      "delivery_destination2": null,
      "delivery_method1": "E",
      "delivery_method2": "E",
      "exception_code": "108002",
      "update_date": "2022-03-07T08:09:31",
      "update_user": null
    },
    {
      "CustId": "975820",
      "Description": "Emp is not authorized for purch with this veh",
      "ExceptionSubscriptionId": "0",
      "HostXref": null,
      "Type": "S",
      "active_flag": "false",
      "create_date": "0001-01-01T00:00:00",
      "create_user": null,
      "delivery_destination1": "HMARKS@DIVERSIFIEDSYS.COM",
      "delivery_destination2": null,
      "delivery_method1": "E",
      "delivery_method2": "E",
      "exception_code": "108401",
      "update_date": "2022-03-07T08:09:31",
      "update_user": null
    },
    {
      "CustId": "975820",
      "Description": "MPG is outside of expected range",
      "ExceptionSubscriptionId": "0",
      "HostXref": null,
      "Type": "N",
      "active_flag": "false",
      "create_date": "0001-01-01T00:00:00",
      "create_user": null,
      "delivery_destination1": "HMARKS@DIVERSIFIEDSYS.COM",
      "delivery_destination2": null,
      "delivery_method1": "E",
      "delivery_method2": "E",
      "exception_code": "108001",
      "update_date": "2022-03-07T08:09:31",
      "update_user": null
    },
    {
      "CustId": "975820",
      "Description": "Vehicle has exceeded its daily fuel limit",
      "ExceptionSubscriptionId": "0",
      "HostXref": null,
      "Type": "S",
      "active_flag": "false",
      "create_date": "0001-01-01T00:00:00",
      "create_user": null,
      "delivery_destination1": "HMARKS@DIVERSIFIEDSYS.COM",
      "delivery_destination2": null,
      "delivery_method1": "E",
      "delivery_method2": "E",
      "exception_code": "108006",
      "update_date": "2022-03-07T08:09:31",
      "update_user": null
    },
    {
      "CustId": "975820",
      "Description": "Cust is restricted from purch at this merch",
      "ExceptionSubscriptionId": "0",
      "HostXref": null,
      "Type": "N",
      "active_flag": "false",
      "create_date": "0001-01-01T00:00:00",
      "create_user": null,
      "delivery_destination1": "HMARKS@DIVERSIFIEDSYS.COM",
      "delivery_destination2": null,
      "delivery_method1": "E",
      "delivery_method2": "E",
      "exception_code": "108308",
      "update_date": "2022-03-07T08:09:31",
      "update_user": null
    },
    {
      "CustId": "975820",
      "Description": "Veh has exceeded its cycle misc product limit",
      "ExceptionSubscriptionId": "0",
      "HostXref": null,
      "Type": "N",
      "active_flag": "false",
      "create_date": "0001-01-01T00:00:00",
      "create_user": null,
      "delivery_destination1": "HMARKS@DIVERSIFIEDSYS.COM",
      "delivery_destination2": null,
      "delivery_method1": "E",
      "delivery_method2": "E",
      "exception_code": "108009",
      "update_date": "2022-03-07T08:09:31",
      "update_user": null
    },
    {
      "CustId": "975820",
      "Description": "Customer is restricted from purchases at site",
      "ExceptionSubscriptionId": "0",
      "HostXref": null,
      "Type": "N",
      "active_flag": "false",
      "create_date": "0001-01-01T00:00:00",
      "create_user": null,
      "delivery_destination1": "HMARKS@DIVERSIFIEDSYS.COM",
      "delivery_destination2": null,
      "delivery_method1": "E",
      "delivery_method2": "E",
      "exception_code": "108307",
      "update_date": "2022-03-07T08:09:31",
      "update_user": null
    },
    {
      "CustId": "975820",
      "Description": "Veh has exceeded its Fleet Services limit",
      "ExceptionSubscriptionId": "0",
      "HostXref": null,
      "Type": "S",
      "active_flag": "false",
      "create_date": "0001-01-01T00:00:00",
      "create_user": null,
      "delivery_destination1": "HMARKS@DIVERSIFIEDSYS.COM",
      "delivery_destination2": null,
      "delivery_method1": "E",
      "delivery_method2": "E",
      "exception_code": "108008",
      "update_date": "2022-03-07T08:09:31",
      "update_user": null
    },
    {
      "CustId": "975820",
      "Description": "Veh is restricted from purch at this merch",
      "ExceptionSubscriptionId": "0",
      "HostXref": null,
      "Type": "N",
      "active_flag": "false",
      "create_date": "0001-01-01T00:00:00",
      "create_user": null,
      "delivery_destination1": "HMARKS@DIVERSIFIEDSYS.COM",
      "delivery_destination2": null,
      "delivery_method1": "E",
      "delivery_method2": "E",
      "exception_code": "108108",
      "update_date": "2022-03-07T08:09:31",
      "update_user": null
    },
    {
      "CustId": "975820",
      "Description": "Odometer entry is out of sequence",
      "ExceptionSubscriptionId": "0",
      "HostXref": null,
      "Type": "S",
      "active_flag": "false",
      "create_date": "0001-01-01T00:00:00",
      "create_user": null,
      "delivery_destination1": "HMARKS@DIVERSIFIEDSYS.COM",
      "delivery_destination2": null,
      "delivery_method1": "E",
      "delivery_method2": "E",
      "exception_code": "108011",
      "update_date": "2022-03-07T08:09:31",
      "update_user": null
    },
    {
      "CustId": "975820",
      "Description": "Emp is restricted from purch at this merch",
      "ExceptionSubscriptionId": "0",
      "HostXref": null,
      "Type": "N",
      "active_flag": "false",
      "create_date": "0001-01-01T00:00:00",
      "create_user": null,
      "delivery_destination1": "HMARKS@DIVERSIFIEDSYS.COM",
      "delivery_destination2": null,
      "delivery_method1": "E",
      "delivery_method2": "E",
      "exception_code": "108208",
      "update_date": "2022-03-07T08:09:31",
      "update_user": null
    }
  ];

  export default settingsExceptionSubscriptions;