const cardsPromptedIdsRewards = {
    "EnrollmentId": 451,
    "EnrolledDate": "2018-02-22T00:00:00Z",
    "AnniversaryDate": null,
    "TierId": 9,
    "AccountCode": "2136645",
    "SystemOfRecord": "iFleet",
    "CurrentBalance": 0,
    "SFAcctId": "2223089",
    "OfferId": "1",
    "TierName": null,
    "CurrentlyEnrolled": true,
    "EligibleDate": null,
    "LateFeeWaivers": 2,
    "LateFeeUsed": 3,
    "CurrentMemberLvlDate": null,
    "TrialStartDate": null,
    "TrialEndDate": null,
    "Channel": "SUI Opt In",
    "PointsHistory": [
      {
        "PointsHistoryId": null,
        "EnrollmentId": null,
        "TransactionDate": "2021-03-01T00:00:00",
        "TransactionVolume": null,
        "Points": 0,
        "PointsBalance": -145001,
        "RedemptionStatus": false,
        "RewardId": null,
        "TransactionAmount": null,
        "RedemptionDetails": null,
        "CumulativePoints": 0,
        "CumulativeCredits": null,
        "CumulativeDebits": null,
        "TransDate": "March, 2021",
        "RedemptionDate": null,
        "RedumptionPoints": 0
      },
      {
        "PointsHistoryId": null,
        "EnrollmentId": null,
        "TransactionDate": "2021-02-01T00:00:00",
        "TransactionVolume": null,
        "Points": 0,
        "PointsBalance": -95001,
        "RedemptionStatus": false,
        "RewardId": null,
        "TransactionAmount": null,
        "RedemptionDetails": null,
        "CumulativePoints": 0,
        "CumulativeCredits": null,
        "CumulativeDebits": null,
        "TransDate": "February, 2021",
        "RedemptionDate": null,
        "RedumptionPoints": 0
      },
      {
        "PointsHistoryId": null,
        "EnrollmentId": null,
        "TransactionDate": "2020-02-01T00:00:00",
        "TransactionVolume": null,
        "Points": 0,
        "PointsBalance": -10001,
        "RedemptionStatus": false,
        "RewardId": null,
        "TransactionAmount": null,
        "RedemptionDetails": null,
        "CumulativePoints": 0,
        "CumulativeCredits": null,
        "CumulativeDebits": null,
        "TransDate": "February, 2020",
        "RedemptionDate": null,
        "RedumptionPoints": 0
      },
      {
        "PointsHistoryId": null,
        "EnrollmentId": null,
        "TransactionDate": "2019-06-01T00:00:00",
        "TransactionVolume": null,
        "Points": 4999,
        "PointsBalance": -5001,
        "RedemptionStatus": false,
        "RewardId": null,
        "TransactionAmount": null,
        "RedemptionDetails": null,
        "CumulativePoints": 0,
        "CumulativeCredits": null,
        "CumulativeDebits": null,
        "TransDate": "June, 2019",
        "RedemptionDate": null,
        "RedumptionPoints": 0
      }
    ],
    "CumulativePoints": 4999,
    "CumulativeDebits": 0,
    "CumulativeCredits": 0,
    "RedeemHistory": [
      {
        "PointsHistoryId": null,
        "EnrollmentId": 451,
        "TransactionDate": "2021-03-02T00:00:00",
        "TransactionVolume": null,
        "Points": 5000,
        "PointsBalance": null,
        "RedemptionStatus": false,
        "RewardId": null,
        "TransactionAmount": null,
        "RedemptionDetails": {
          "RedemptionDetailId": 0,
          "PointsHistoryId": null,
          "RedemptionProcessed": null,
          "FirstName": "ff redemer fname",
          "LastName": "ff redemer lname",
          "AddressLine1": null,
          "AddressLine2": null,
          "City": null,
          "State": null,
          "Zip": null,
          "Phone": null,
          "RedemptionDate": "0001-01-01T00:00:00",
          "RedeemerEmail": null,
          "BusinessName": null,
          "RecipientFirstName": null,
          "RecipientLastName": null
        },
        "CumulativePoints": null,
        "CumulativeCredits": null,
        "CumulativeDebits": null,
        "TransDate": null,
        "RedemptionDate": null,
        "RedumptionPoints": 0
      },
      {
        "PointsHistoryId": null,
        "EnrollmentId": 451,
        "TransactionDate": "2021-03-02T00:00:00",
        "TransactionVolume": null,
        "Points": 5000,
        "PointsBalance": null,
        "RedemptionStatus": false,
        "RewardId": null,
        "TransactionAmount": null,
        "RedemptionDetails": {
          "RedemptionDetailId": 0,
          "PointsHistoryId": null,
          "RedemptionProcessed": null,
          "FirstName": "efrgrg",
          "LastName": "rtgryhyn",
          "AddressLine1": null,
          "AddressLine2": null,
          "City": null,
          "State": null,
          "Zip": null,
          "Phone": null,
          "RedemptionDate": "0001-01-01T00:00:00",
          "RedeemerEmail": null,
          "BusinessName": null,
          "RecipientFirstName": null,
          "RecipientLastName": null
        },
        "CumulativePoints": null,
        "CumulativeCredits": null,
        "CumulativeDebits": null,
        "TransDate": null,
        "RedemptionDate": null,
        "RedumptionPoints": 0
      },
      {
        "PointsHistoryId": null,
        "EnrollmentId": 451,
        "TransactionDate": "2021-03-02T00:00:00",
        "TransactionVolume": null,
        "Points": 5000,
        "PointsBalance": null,
        "RedemptionStatus": false,
        "RewardId": null,
        "TransactionAmount": null,
        "RedemptionDetails": {
          "RedemptionDetailId": 0,
          "PointsHistoryId": null,
          "RedemptionProcessed": null,
          "FirstName": "sadasd",
          "LastName": "sddasd",
          "AddressLine1": null,
          "AddressLine2": null,
          "City": null,
          "State": null,
          "Zip": null,
          "Phone": null,
          "RedemptionDate": "0001-01-01T00:00:00",
          "RedeemerEmail": null,
          "BusinessName": null,
          "RecipientFirstName": null,
          "RecipientLastName": null
        },
        "CumulativePoints": null,
        "CumulativeCredits": null,
        "CumulativeDebits": null,
        "TransDate": null,
        "RedemptionDate": null,
        "RedumptionPoints": 0
      },
      {
        "PointsHistoryId": null,
        "EnrollmentId": 451,
        "TransactionDate": "2021-03-02T00:00:00",
        "TransactionVolume": null,
        "Points": 5000,
        "PointsBalance": null,
        "RedemptionStatus": false,
        "RewardId": null,
        "TransactionAmount": null,
        "RedemptionDetails": {
          "RedemptionDetailId": 0,
          "PointsHistoryId": null,
          "RedemptionProcessed": null,
          "FirstName": "ghghg",
          "LastName": "dasdasd",
          "AddressLine1": null,
          "AddressLine2": null,
          "City": null,
          "State": null,
          "Zip": null,
          "Phone": null,
          "RedemptionDate": "0001-01-01T00:00:00",
          "RedeemerEmail": null,
          "BusinessName": null,
          "RecipientFirstName": null,
          "RecipientLastName": null
        },
        "CumulativePoints": null,
        "CumulativeCredits": null,
        "CumulativeDebits": null,
        "TransDate": null,
        "RedemptionDate": null,
        "RedumptionPoints": 0
      },
      {
        "PointsHistoryId": null,
        "EnrollmentId": 451,
        "TransactionDate": "2021-03-02T00:00:00",
        "TransactionVolume": null,
        "Points": 5000,
        "PointsBalance": null,
        "RedemptionStatus": false,
        "RewardId": null,
        "TransactionAmount": null,
        "RedemptionDetails": {
          "RedemptionDetailId": 0,
          "PointsHistoryId": null,
          "RedemptionProcessed": null,
          "FirstName": "sasad",
          "LastName": "asdasd",
          "AddressLine1": null,
          "AddressLine2": null,
          "City": null,
          "State": null,
          "Zip": null,
          "Phone": null,
          "RedemptionDate": "0001-01-01T00:00:00",
          "RedeemerEmail": null,
          "BusinessName": null,
          "RecipientFirstName": null,
          "RecipientLastName": null
        },
        "CumulativePoints": null,
        "CumulativeCredits": null,
        "CumulativeDebits": null,
        "TransDate": null,
        "RedemptionDate": null,
        "RedumptionPoints": 0
      },
      {
        "PointsHistoryId": null,
        "EnrollmentId": 451,
        "TransactionDate": "2021-03-02T00:00:00",
        "TransactionVolume": null,
        "Points": 5000,
        "PointsBalance": null,
        "RedemptionStatus": false,
        "RewardId": null,
        "TransactionAmount": null,
        "RedemptionDetails": {
          "RedemptionDetailId": 0,
          "PointsHistoryId": null,
          "RedemptionProcessed": null,
          "FirstName": "sasad",
          "LastName": "asdasd",
          "AddressLine1": null,
          "AddressLine2": null,
          "City": null,
          "State": null,
          "Zip": null,
          "Phone": null,
          "RedemptionDate": "0001-01-01T00:00:00",
          "RedeemerEmail": null,
          "BusinessName": null,
          "RecipientFirstName": null,
          "RecipientLastName": null
        },
        "CumulativePoints": null,
        "CumulativeCredits": null,
        "CumulativeDebits": null,
        "TransDate": null,
        "RedemptionDate": null,
        "RedumptionPoints": 0
      },
      {
        "PointsHistoryId": null,
        "EnrollmentId": 451,
        "TransactionDate": "2021-03-02T00:00:00",
        "TransactionVolume": null,
        "Points": 5000,
        "PointsBalance": null,
        "RedemptionStatus": false,
        "RewardId": null,
        "TransactionAmount": null,
        "RedemptionDetails": {
          "RedemptionDetailId": 0,
          "PointsHistoryId": null,
          "RedemptionProcessed": null,
          "FirstName": "ff redeemer fname",
          "LastName": "ff redemer lname",
          "AddressLine1": null,
          "AddressLine2": null,
          "City": null,
          "State": null,
          "Zip": null,
          "Phone": null,
          "RedemptionDate": "0001-01-01T00:00:00",
          "RedeemerEmail": null,
          "BusinessName": null,
          "RecipientFirstName": null,
          "RecipientLastName": null
        },
        "CumulativePoints": null,
        "CumulativeCredits": null,
        "CumulativeDebits": null,
        "TransDate": null,
        "RedemptionDate": null,
        "RedumptionPoints": 0
      },
      {
        "PointsHistoryId": null,
        "EnrollmentId": 451,
        "TransactionDate": "2021-03-02T00:00:00",
        "TransactionVolume": null,
        "Points": 5000,
        "PointsBalance": null,
        "RedemptionStatus": false,
        "RewardId": null,
        "TransactionAmount": null,
        "RedemptionDetails": {
          "RedemptionDetailId": 0,
          "PointsHistoryId": null,
          "RedemptionProcessed": null,
          "FirstName": "ghghg",
          "LastName": "dasdasd",
          "AddressLine1": null,
          "AddressLine2": null,
          "City": null,
          "State": null,
          "Zip": null,
          "Phone": null,
          "RedemptionDate": "0001-01-01T00:00:00",
          "RedeemerEmail": null,
          "BusinessName": null,
          "RecipientFirstName": null,
          "RecipientLastName": null
        },
        "CumulativePoints": null,
        "CumulativeCredits": null,
        "CumulativeDebits": null,
        "TransDate": null,
        "RedemptionDate": null,
        "RedumptionPoints": 0
      },
      {
        "PointsHistoryId": null,
        "EnrollmentId": 451,
        "TransactionDate": "2021-03-02T00:00:00",
        "TransactionVolume": null,
        "Points": 5000,
        "PointsBalance": null,
        "RedemptionStatus": false,
        "RewardId": null,
        "TransactionAmount": null,
        "RedemptionDetails": {
          "RedemptionDetailId": 0,
          "PointsHistoryId": null,
          "RedemptionProcessed": null,
          "FirstName": "ghghg",
          "LastName": "dasdasd",
          "AddressLine1": null,
          "AddressLine2": null,
          "City": null,
          "State": null,
          "Zip": null,
          "Phone": null,
          "RedemptionDate": "0001-01-01T00:00:00",
          "RedeemerEmail": null,
          "BusinessName": null,
          "RecipientFirstName": null,
          "RecipientLastName": null
        },
        "CumulativePoints": null,
        "CumulativeCredits": null,
        "CumulativeDebits": null,
        "TransDate": null,
        "RedemptionDate": null,
        "RedumptionPoints": 0
      },
      {
        "PointsHistoryId": null,
        "EnrollmentId": 451,
        "TransactionDate": "2021-03-02T00:00:00",
        "TransactionVolume": null,
        "Points": 5000,
        "PointsBalance": null,
        "RedemptionStatus": false,
        "RewardId": null,
        "TransactionAmount": null,
        "RedemptionDetails": {
          "RedemptionDetailId": 0,
          "PointsHistoryId": null,
          "RedemptionProcessed": null,
          "FirstName": "sasad",
          "LastName": "asdasd",
          "AddressLine1": null,
          "AddressLine2": null,
          "City": null,
          "State": null,
          "Zip": null,
          "Phone": null,
          "RedemptionDate": "0001-01-01T00:00:00",
          "RedeemerEmail": null,
          "BusinessName": null,
          "RecipientFirstName": null,
          "RecipientLastName": null
        },
        "CumulativePoints": null,
        "CumulativeCredits": null,
        "CumulativeDebits": null,
        "TransDate": null,
        "RedemptionDate": null,
        "RedumptionPoints": 0
      },
      {
        "PointsHistoryId": null,
        "EnrollmentId": 451,
        "TransactionDate": "2021-02-25T00:00:00",
        "TransactionVolume": null,
        "Points": 5000,
        "PointsBalance": null,
        "RedemptionStatus": false,
        "RewardId": null,
        "TransactionAmount": null,
        "RedemptionDetails": {
          "RedemptionDetailId": 0,
          "PointsHistoryId": null,
          "RedemptionProcessed": null,
          "FirstName": "sdas",
          "LastName": "asdasd",
          "AddressLine1": null,
          "AddressLine2": null,
          "City": null,
          "State": null,
          "Zip": null,
          "Phone": null,
          "RedemptionDate": "0001-01-01T00:00:00",
          "RedeemerEmail": null,
          "BusinessName": null,
          "RecipientFirstName": null,
          "RecipientLastName": null
        },
        "CumulativePoints": null,
        "CumulativeCredits": null,
        "CumulativeDebits": null,
        "TransDate": null,
        "RedemptionDate": null,
        "RedumptionPoints": 0
      },
      {
        "PointsHistoryId": null,
        "EnrollmentId": 451,
        "TransactionDate": "2021-02-25T00:00:00",
        "TransactionVolume": null,
        "Points": 5000,
        "PointsBalance": null,
        "RedemptionStatus": false,
        "RewardId": null,
        "TransactionAmount": null,
        "RedemptionDetails": {
          "RedemptionDetailId": 0,
          "PointsHistoryId": null,
          "RedemptionProcessed": null,
          "FirstName": "sadasd",
          "LastName": "sddasd",
          "AddressLine1": null,
          "AddressLine2": null,
          "City": null,
          "State": null,
          "Zip": null,
          "Phone": null,
          "RedemptionDate": "0001-01-01T00:00:00",
          "RedeemerEmail": null,
          "BusinessName": null,
          "RecipientFirstName": null,
          "RecipientLastName": null
        },
        "CumulativePoints": null,
        "CumulativeCredits": null,
        "CumulativeDebits": null,
        "TransDate": null,
        "RedemptionDate": null,
        "RedumptionPoints": 0
      },
      {
        "PointsHistoryId": null,
        "EnrollmentId": 451,
        "TransactionDate": "2021-02-24T00:00:00",
        "TransactionVolume": null,
        "Points": 5000,
        "PointsBalance": null,
        "RedemptionStatus": false,
        "RewardId": null,
        "TransactionAmount": null,
        "RedemptionDetails": {
          "RedemptionDetailId": 0,
          "PointsHistoryId": null,
          "RedemptionProcessed": null,
          "FirstName": "edge pavan test",
          "LastName": "redmer lanst name",
          "AddressLine1": null,
          "AddressLine2": null,
          "City": null,
          "State": null,
          "Zip": null,
          "Phone": null,
          "RedemptionDate": "0001-01-01T00:00:00",
          "RedeemerEmail": null,
          "BusinessName": null,
          "RecipientFirstName": null,
          "RecipientLastName": null
        },
        "CumulativePoints": null,
        "CumulativeCredits": null,
        "CumulativeDebits": null,
        "TransDate": null,
        "RedemptionDate": null,
        "RedumptionPoints": 0
      },
      {
        "PointsHistoryId": null,
        "EnrollmentId": 451,
        "TransactionDate": "2021-02-23T00:00:00",
        "TransactionVolume": null,
        "Points": 5000,
        "PointsBalance": null,
        "RedemptionStatus": false,
        "RewardId": null,
        "TransactionAmount": null,
        "RedemptionDetails": {
          "RedemptionDetailId": 0,
          "PointsHistoryId": null,
          "RedemptionProcessed": null,
          "FirstName": "Nitasha",
          "LastName": "Singla",
          "AddressLine1": null,
          "AddressLine2": null,
          "City": null,
          "State": null,
          "Zip": null,
          "Phone": null,
          "RedemptionDate": "0001-01-01T00:00:00",
          "RedeemerEmail": null,
          "BusinessName": null,
          "RecipientFirstName": null,
          "RecipientLastName": null
        },
        "CumulativePoints": null,
        "CumulativeCredits": null,
        "CumulativeDebits": null,
        "TransDate": null,
        "RedemptionDate": null,
        "RedumptionPoints": 0
      },
      {
        "PointsHistoryId": null,
        "EnrollmentId": 451,
        "TransactionDate": "2021-02-23T00:00:00",
        "TransactionVolume": null,
        "Points": 5000,
        "PointsBalance": null,
        "RedemptionStatus": false,
        "RewardId": null,
        "TransactionAmount": null,
        "RedemptionDetails": {
          "RedemptionDetailId": 0,
          "PointsHistoryId": null,
          "RedemptionProcessed": null,
          "FirstName": "Nitasha",
          "LastName": "Singla",
          "AddressLine1": null,
          "AddressLine2": null,
          "City": null,
          "State": null,
          "Zip": null,
          "Phone": null,
          "RedemptionDate": "0001-01-01T00:00:00",
          "RedeemerEmail": null,
          "BusinessName": null,
          "RecipientFirstName": null,
          "RecipientLastName": null
        },
        "CumulativePoints": null,
        "CumulativeCredits": null,
        "CumulativeDebits": null,
        "TransDate": null,
        "RedemptionDate": null,
        "RedumptionPoints": 0
      },
      {
        "PointsHistoryId": null,
        "EnrollmentId": 451,
        "TransactionDate": "2021-02-23T00:00:00",
        "TransactionVolume": null,
        "Points": 5000,
        "PointsBalance": null,
        "RedemptionStatus": false,
        "RewardId": null,
        "TransactionAmount": null,
        "RedemptionDetails": {
          "RedemptionDetailId": 0,
          "PointsHistoryId": null,
          "RedemptionProcessed": null,
          "FirstName": "gggg",
          "LastName": "Singla",
          "AddressLine1": null,
          "AddressLine2": null,
          "City": null,
          "State": null,
          "Zip": null,
          "Phone": null,
          "RedemptionDate": "0001-01-01T00:00:00",
          "RedeemerEmail": null,
          "BusinessName": null,
          "RecipientFirstName": null,
          "RecipientLastName": null
        },
        "CumulativePoints": null,
        "CumulativeCredits": null,
        "CumulativeDebits": null,
        "TransDate": null,
        "RedemptionDate": null,
        "RedumptionPoints": 0
      },
      {
        "PointsHistoryId": null,
        "EnrollmentId": 451,
        "TransactionDate": "2021-02-23T00:00:00",
        "TransactionVolume": null,
        "Points": 5000,
        "PointsBalance": null,
        "RedemptionStatus": false,
        "RewardId": null,
        "TransactionAmount": null,
        "RedemptionDetails": {
          "RedemptionDetailId": 0,
          "PointsHistoryId": null,
          "RedemptionProcessed": null,
          "FirstName": "Nits",
          "LastName": "Singla",
          "AddressLine1": null,
          "AddressLine2": null,
          "City": null,
          "State": null,
          "Zip": null,
          "Phone": null,
          "RedemptionDate": "0001-01-01T00:00:00",
          "RedeemerEmail": null,
          "BusinessName": null,
          "RecipientFirstName": null,
          "RecipientLastName": null
        },
        "CumulativePoints": null,
        "CumulativeCredits": null,
        "CumulativeDebits": null,
        "TransDate": null,
        "RedemptionDate": null,
        "RedumptionPoints": 0
      },
      {
        "PointsHistoryId": null,
        "EnrollmentId": 451,
        "TransactionDate": "2021-02-23T00:00:00",
        "TransactionVolume": null,
        "Points": 10000,
        "PointsBalance": null,
        "RedemptionStatus": false,
        "RewardId": null,
        "TransactionAmount": null,
        "RedemptionDetails": {
          "RedemptionDetailId": 0,
          "PointsHistoryId": null,
          "RedemptionProcessed": null,
          "FirstName": "Nitasha",
          "LastName": "Singla",
          "AddressLine1": null,
          "AddressLine2": null,
          "City": null,
          "State": null,
          "Zip": null,
          "Phone": null,
          "RedemptionDate": "0001-01-01T00:00:00",
          "RedeemerEmail": null,
          "BusinessName": null,
          "RecipientFirstName": null,
          "RecipientLastName": null
        },
        "CumulativePoints": null,
        "CumulativeCredits": null,
        "CumulativeDebits": null,
        "TransDate": null,
        "RedemptionDate": null,
        "RedumptionPoints": 0
      },
      {
        "PointsHistoryId": null,
        "EnrollmentId": 451,
        "TransactionDate": "2021-02-23T00:00:00",
        "TransactionVolume": null,
        "Points": 5000,
        "PointsBalance": null,
        "RedemptionStatus": false,
        "RewardId": null,
        "TransactionAmount": null,
        "RedemptionDetails": {
          "RedemptionDetailId": 0,
          "PointsHistoryId": null,
          "RedemptionProcessed": null,
          "FirstName": "Nitasha",
          "LastName": "Singla",
          "AddressLine1": null,
          "AddressLine2": null,
          "City": null,
          "State": null,
          "Zip": null,
          "Phone": null,
          "RedemptionDate": "0001-01-01T00:00:00",
          "RedeemerEmail": null,
          "BusinessName": null,
          "RecipientFirstName": null,
          "RecipientLastName": null
        },
        "CumulativePoints": null,
        "CumulativeCredits": null,
        "CumulativeDebits": null,
        "TransDate": null,
        "RedemptionDate": null,
        "RedumptionPoints": 0
      },
      {
        "PointsHistoryId": null,
        "EnrollmentId": 451,
        "TransactionDate": "2021-02-23T00:00:00",
        "TransactionVolume": null,
        "Points": 5000,
        "PointsBalance": null,
        "RedemptionStatus": false,
        "RewardId": null,
        "TransactionAmount": null,
        "RedemptionDetails": {
          "RedemptionDetailId": 0,
          "PointsHistoryId": null,
          "RedemptionProcessed": null,
          "FirstName": "One",
          "LastName": "One",
          "AddressLine1": null,
          "AddressLine2": null,
          "City": null,
          "State": null,
          "Zip": null,
          "Phone": null,
          "RedemptionDate": "0001-01-01T00:00:00",
          "RedeemerEmail": null,
          "BusinessName": null,
          "RecipientFirstName": null,
          "RecipientLastName": null
        },
        "CumulativePoints": null,
        "CumulativeCredits": null,
        "CumulativeDebits": null,
        "TransDate": null,
        "RedemptionDate": null,
        "RedumptionPoints": 0
      },
      {
        "PointsHistoryId": null,
        "EnrollmentId": 451,
        "TransactionDate": "2021-02-23T00:00:00",
        "TransactionVolume": null,
        "Points": 5000,
        "PointsBalance": null,
        "RedemptionStatus": false,
        "RewardId": null,
        "TransactionAmount": null,
        "RedemptionDetails": {
          "RedemptionDetailId": 0,
          "PointsHistoryId": null,
          "RedemptionProcessed": null,
          "FirstName": "two",
          "LastName": "two",
          "AddressLine1": null,
          "AddressLine2": null,
          "City": null,
          "State": null,
          "Zip": null,
          "Phone": null,
          "RedemptionDate": "0001-01-01T00:00:00",
          "RedeemerEmail": null,
          "BusinessName": null,
          "RecipientFirstName": null,
          "RecipientLastName": null
        },
        "CumulativePoints": null,
        "CumulativeCredits": null,
        "CumulativeDebits": null,
        "TransDate": null,
        "RedemptionDate": null,
        "RedumptionPoints": 0
      },
      {
        "PointsHistoryId": null,
        "EnrollmentId": 451,
        "TransactionDate": "2021-02-23T00:00:00",
        "TransactionVolume": null,
        "Points": 7500,
        "PointsBalance": null,
        "RedemptionStatus": false,
        "RewardId": null,
        "TransactionAmount": null,
        "RedemptionDetails": {
          "RedemptionDetailId": 0,
          "PointsHistoryId": null,
          "RedemptionProcessed": null,
          "FirstName": "ghghg",
          "LastName": "dasdasd",
          "AddressLine1": null,
          "AddressLine2": null,
          "City": null,
          "State": null,
          "Zip": null,
          "Phone": null,
          "RedemptionDate": "0001-01-01T00:00:00",
          "RedeemerEmail": null,
          "BusinessName": null,
          "RecipientFirstName": null,
          "RecipientLastName": null
        },
        "CumulativePoints": null,
        "CumulativeCredits": null,
        "CumulativeDebits": null,
        "TransDate": null,
        "RedemptionDate": null,
        "RedumptionPoints": 0
      },
      {
        "PointsHistoryId": null,
        "EnrollmentId": 451,
        "TransactionDate": "2021-02-23T00:00:00",
        "TransactionVolume": null,
        "Points": 7500,
        "PointsBalance": null,
        "RedemptionStatus": false,
        "RewardId": null,
        "TransactionAmount": null,
        "RedemptionDetails": {
          "RedemptionDetailId": 0,
          "PointsHistoryId": null,
          "RedemptionProcessed": null,
          "FirstName": "ghghg",
          "LastName": "dasdasd",
          "AddressLine1": null,
          "AddressLine2": null,
          "City": null,
          "State": null,
          "Zip": null,
          "Phone": null,
          "RedemptionDate": "0001-01-01T00:00:00",
          "RedeemerEmail": null,
          "BusinessName": null,
          "RecipientFirstName": null,
          "RecipientLastName": null
        },
        "CumulativePoints": null,
        "CumulativeCredits": null,
        "CumulativeDebits": null,
        "TransDate": null,
        "RedemptionDate": null,
        "RedumptionPoints": 0
      },
      {
        "PointsHistoryId": null,
        "EnrollmentId": 451,
        "TransactionDate": "2021-02-23T00:00:00",
        "TransactionVolume": null,
        "Points": 5000,
        "PointsBalance": null,
        "RedemptionStatus": false,
        "RewardId": null,
        "TransactionAmount": null,
        "RedemptionDetails": {
          "RedemptionDetailId": 0,
          "PointsHistoryId": null,
          "RedemptionProcessed": null,
          "FirstName": "ghghg",
          "LastName": "dasdasd",
          "AddressLine1": null,
          "AddressLine2": null,
          "City": null,
          "State": null,
          "Zip": null,
          "Phone": null,
          "RedemptionDate": "0001-01-01T00:00:00",
          "RedeemerEmail": null,
          "BusinessName": null,
          "RecipientFirstName": null,
          "RecipientLastName": null
        },
        "CumulativePoints": null,
        "CumulativeCredits": null,
        "CumulativeDebits": null,
        "TransDate": null,
        "RedemptionDate": null,
        "RedumptionPoints": 0
      },
      {
        "PointsHistoryId": null,
        "EnrollmentId": 451,
        "TransactionDate": "2021-02-23T00:00:00",
        "TransactionVolume": null,
        "Points": 5000,
        "PointsBalance": null,
        "RedemptionStatus": false,
        "RewardId": null,
        "TransactionAmount": null,
        "RedemptionDetails": {
          "RedemptionDetailId": 0,
          "PointsHistoryId": null,
          "RedemptionProcessed": null,
          "FirstName": "sdas",
          "LastName": "asdasd",
          "AddressLine1": null,
          "AddressLine2": null,
          "City": null,
          "State": null,
          "Zip": null,
          "Phone": null,
          "RedemptionDate": "0001-01-01T00:00:00",
          "RedeemerEmail": null,
          "BusinessName": null,
          "RecipientFirstName": null,
          "RecipientLastName": null
        },
        "CumulativePoints": null,
        "CumulativeCredits": null,
        "CumulativeDebits": null,
        "TransDate": null,
        "RedemptionDate": null,
        "RedumptionPoints": 0
      },
      {
        "PointsHistoryId": null,
        "EnrollmentId": 451,
        "TransactionDate": "2020-02-06T00:00:00",
        "TransactionVolume": null,
        "Points": 5000,
        "PointsBalance": null,
        "RedemptionStatus": false,
        "RewardId": null,
        "TransactionAmount": null,
        "RedemptionDetails": {
          "RedemptionDetailId": 0,
          "PointsHistoryId": null,
          "RedemptionProcessed": null,
          "FirstName": "fc",
          "LastName": "nc",
          "AddressLine1": null,
          "AddressLine2": null,
          "City": null,
          "State": null,
          "Zip": null,
          "Phone": null,
          "RedemptionDate": "0001-01-01T00:00:00",
          "RedeemerEmail": null,
          "BusinessName": null,
          "RecipientFirstName": null,
          "RecipientLastName": null
        },
        "CumulativePoints": null,
        "CumulativeCredits": null,
        "CumulativeDebits": null,
        "TransDate": null,
        "RedemptionDate": null,
        "RedumptionPoints": 0
      },
      {
        "PointsHistoryId": null,
        "EnrollmentId": 451,
        "TransactionDate": "2019-06-18T00:00:00",
        "TransactionVolume": null,
        "Points": 5000,
        "PointsBalance": null,
        "RedemptionStatus": false,
        "RewardId": null,
        "TransactionAmount": null,
        "RedemptionDetails": {
          "RedemptionDetailId": 0,
          "PointsHistoryId": null,
          "RedemptionProcessed": null,
          "FirstName": "June",
          "LastName": "Test",
          "AddressLine1": null,
          "AddressLine2": null,
          "City": null,
          "State": null,
          "Zip": null,
          "Phone": null,
          "RedemptionDate": "0001-01-01T00:00:00",
          "RedeemerEmail": null,
          "BusinessName": null,
          "RecipientFirstName": null,
          "RecipientLastName": null
        },
        "CumulativePoints": null,
        "CumulativeCredits": null,
        "CumulativeDebits": null,
        "TransDate": null,
        "RedemptionDate": null,
        "RedumptionPoints": 0
      },
      {
        "PointsHistoryId": null,
        "EnrollmentId": 451,
        "TransactionDate": "2019-06-18T00:00:00",
        "TransactionVolume": null,
        "Points": 5000,
        "PointsBalance": null,
        "RedemptionStatus": false,
        "RewardId": null,
        "TransactionAmount": null,
        "RedemptionDetails": {
          "RedemptionDetailId": 0,
          "PointsHistoryId": null,
          "RedemptionProcessed": null,
          "FirstName": "Latest",
          "LastName": "One",
          "AddressLine1": null,
          "AddressLine2": null,
          "City": null,
          "State": null,
          "Zip": null,
          "Phone": null,
          "RedemptionDate": "0001-01-01T00:00:00",
          "RedeemerEmail": null,
          "BusinessName": null,
          "RecipientFirstName": null,
          "RecipientLastName": null
        },
        "CumulativePoints": null,
        "CumulativeCredits": null,
        "CumulativeDebits": null,
        "TransDate": null,
        "RedemptionDate": null,
        "RedumptionPoints": 0
      }
    ],
    "Email": null,
    "Fname": null,
    "Lname": null
  };

  export default cardsPromptedIdsRewards;