const cardsProfilesEdit = {
    "PUT PAYLOAD":  {
        0: {"Allow_loc": null, "Allow_nonfuel": "false", "AllowedFuels": "A", "AllowedFuelsDescription": "All Fuels"},
1: {"Allow_loc": null,
"Allow_nonfuel": "false",
"AllowedFuels": "A",
"AllowedFuelsDescription": "All Fuels",
"CardRestrictionType": null,
"CardTypeId": "1",
"CardTypeIdDescription": "Driver",
"CycleLimits": [{}, {}, {}, {}],
"DailyLimits": [{TransactionCategory: null, cycleType: null, dailyDollarLimit: null, dailyDollarReport: "false"}],
"EmployeeNumberFlag": null,
"FleetHostRef": null,
"FleetProfileNum": "01",
"LastUpdateDate": "2022-01-20T01:12:07",
"NewCardOnProfile": "false",
"ProductType": null,
"PromptedIdType": "N",
"ReportInvalidFuel": "false",
"ReportInvalidTime": "false",
"Restrict_lev3": null,
"TransactionLimits": [{TransactionDollarLimit: null, TransactionQuantityLimit: "122", transactionQuantityReport: true}],
"allowOnlineRiskControlChange": "false",
"allowVRNValidationChange": "false",
"cardOnProfile": "24",
"cardTypeID": "1",
"customerCardTypeVelocityProfileID": "3103491",
"customerId": "975820",
"dayEndTime": "00:00:00",
"dayStartTime": "00:00:00",
"defaultOnlineRiskControlId": null,
"enforceOdometerValidation": "false",
"enforceVRNValidation": "false",
"excludePremiumFuels": null,
"fillLimit": null,
"isActive": "true",
"isDefault": "false",
"isFullTimeUse": "true",
"maxFillValue": null,
"maxNumberTrxAnnual": "0",
"maxNumberTrxDay": "0",
"maxNumberTrxMonth": "0",
"maxNumberTrxWeek": "0",
"maxTrxValueAnnual": "0",
"maxTrxValueDay": "0",
"maxTrxValueMonth": "0",
"maxTrxValueWeek": "0",
"maxTrxVolumeAnnual": "0",
"maxTrxVolumeDay": "0",
"maxTrxVolumeMonth": "0",
"maxTrxVolumeWeek": "0",
"otherProductsAtFuelSites": null,
"otherTPMServices": null,
"profileName": "01 - Fuel Only2",
"transactionAmount": null,
"transactionCount": null,
"useOnDays": "YYYYYYY",
"useOnFriday": "true",
"useOnMonday": "true",
"useOnSaturday": "true",
"useOnSunday": "true",
"useOnThursday": "true",
"useOnTuesday": "true",
"useOnWednesday": "true"}}};

export default cardsProfilesEdit;