const cardsOrderDepartments = [
    {
      "CustomerID": null,
      "DeptId": "180299",
      "DeptName": "testdepfei0204",
      "DeptNum": null,
      "FleetId": null,
      "HostXRef": null,
      "Language": null,
      "LastUpdateDate": "0001-01-01T00:00:00",
      "ReqUser": null,
      "Status": null,
      "UpdatedUser": null
    },
    {
      "CustomerID": null,
      "DeptId": "180310",
      "DeptName": "v1NewDept",
      "DeptNum": null,
      "FleetId": null,
      "HostXRef": null,
      "Language": null,
      "LastUpdateDate": "0001-01-01T00:00:00",
      "ReqUser": null,
      "Status": null,
      "UpdatedUser": null
    },
    {
      "CustomerID": null,
      "DeptId": "180274",
      "DeptName": null,
      "DeptNum": null,
      "FleetId": null,
      "HostXRef": null,
      "Language": null,
      "LastUpdateDate": "0001-01-01T00:00:00",
      "ReqUser": null,
      "Status": null,
      "UpdatedUser": null
    },
    {
      "CustomerID": null,
      "DeptId": "180298",
      "DeptName": "tdeptcd0204",
      "DeptNum": null,
      "FleetId": null,
      "HostXRef": null,
      "Language": null,
      "LastUpdateDate": "0001-01-01T00:00:00",
      "ReqUser": null,
      "Status": null,
      "UpdatedUser": null
    },
    {
      "CustomerID": null,
      "DeptId": "180275",
      "DeptName": "1111UCX",
      "DeptNum": null,
      "FleetId": null,
      "HostXRef": null,
      "Language": null,
      "LastUpdateDate": "0001-01-01T00:00:00",
      "ReqUser": null,
      "Status": null,
      "UpdatedUser": null
    },
    {
      "CustomerID": null,
      "DeptId": "180372",
      "DeptName": "r45",
      "DeptNum": null,
      "FleetId": null,
      "HostXRef": null,
      "Language": null,
      "LastUpdateDate": "0001-01-01T00:00:00",
      "ReqUser": null,
      "Status": null,
      "UpdatedUser": null
    },
    {
      "CustomerID": null,
      "DeptId": "180376",
      "DeptName": "1111",
      "DeptNum": null,
      "FleetId": null,
      "HostXRef": null,
      "Language": null,
      "LastUpdateDate": "0001-01-01T00:00:00",
      "ReqUser": null,
      "Status": null,
      "UpdatedUser": null
    },
    {
      "CustomerID": null,
      "DeptId": "180281",
      "DeptName": "DJTrucking",
      "DeptNum": null,
      "FleetId": null,
      "HostXRef": null,
      "Language": null,
      "LastUpdateDate": "0001-01-01T00:00:00",
      "ReqUser": null,
      "Status": null,
      "UpdatedUser": null
    },
    {
      "CustomerID": null,
      "DeptId": "180282",
      "DeptName": "1113UCX",
      "DeptNum": null,
      "FleetId": null,
      "HostXRef": null,
      "Language": null,
      "LastUpdateDate": "0001-01-01T00:00:00",
      "ReqUser": null,
      "Status": null,
      "UpdatedUser": null
    },
    {
      "CustomerID": null,
      "DeptId": "180387",
      "DeptName": "testdept",
      "DeptNum": null,
      "FleetId": null,
      "HostXRef": null,
      "Language": null,
      "LastUpdateDate": "0001-01-01T00:00:00",
      "ReqUser": null,
      "Status": null,
      "UpdatedUser": null
    },
    {
      "CustomerID": null,
      "DeptId": "180404",
      "DeptName": "aNewDept",
      "DeptNum": null,
      "FleetId": null,
      "HostXRef": null,
      "Language": null,
      "LastUpdateDate": "0001-01-01T00:00:00",
      "ReqUser": null,
      "Status": null,
      "UpdatedUser": null
    },
    {
      "CustomerID": null,
      "DeptId": "180279",
      "DeptName": "1112UCX",
      "DeptNum": null,
      "FleetId": null,
      "HostXRef": null,
      "Language": null,
      "LastUpdateDate": "0001-01-01T00:00:00",
      "ReqUser": null,
      "Status": null,
      "UpdatedUser": null
    },
    {
      "CustomerID": null,
      "DeptId": "180385",
      "DeptName": "test0219newdp",
      "DeptNum": null,
      "FleetId": null,
      "HostXRef": null,
      "Language": null,
      "LastUpdateDate": "0001-01-01T00:00:00",
      "ReqUser": null,
      "Status": null,
      "UpdatedUser": null
    },
    {
      "CustomerID": null,
      "DeptId": "180405",
      "DeptName": "aNewDept1",
      "DeptNum": null,
      "FleetId": null,
      "HostXRef": null,
      "Language": null,
      "LastUpdateDate": "0001-01-01T00:00:00",
      "ReqUser": null,
      "Status": null,
      "UpdatedUser": null
    },
    {
      "CustomerID": null,
      "DeptId": "180406",
      "DeptName": "v2newDeptA",
      "DeptNum": null,
      "FleetId": null,
      "HostXRef": null,
      "Language": null,
      "LastUpdateDate": "0001-01-01T00:00:00",
      "ReqUser": null,
      "Status": null,
      "UpdatedUser": null
    },
    {
      "CustomerID": null,
      "DeptId": "180416",
      "DeptName": "vehicle",
      "DeptNum": null,
      "FleetId": null,
      "HostXRef": null,
      "Language": null,
      "LastUpdateDate": "0001-01-01T00:00:00",
      "ReqUser": null,
      "Status": null,
      "UpdatedUser": null
    },
    {
      "CustomerID": null,
      "DeptId": "180379",
      "DeptName": "newdparua0217",
      "DeptNum": null,
      "FleetId": null,
      "HostXRef": null,
      "Language": null,
      "LastUpdateDate": "0001-01-01T00:00:00",
      "ReqUser": null,
      "Status": null,
      "UpdatedUser": null
    },
    {
      "CustomerID": null,
      "DeptId": "180414",
      "DeptName": "testdeptarcooc",
      "DeptNum": null,
      "FleetId": null,
      "HostXRef": null,
      "Language": null,
      "LastUpdateDate": "0001-01-01T00:00:00",
      "ReqUser": null,
      "Status": null,
      "UpdatedUser": null
    },
    {
      "CustomerID": null,
      "DeptId": "180415",
      "DeptName": "45678",
      "DeptNum": null,
      "FleetId": null,
      "HostXRef": null,
      "Language": null,
      "LastUpdateDate": "0001-01-01T00:00:00",
      "ReqUser": null,
      "Status": null,
      "UpdatedUser": null
    },
    {
      "CustomerID": null,
      "DeptId": "180311",
      "DeptName": "v2NewDept",
      "DeptNum": null,
      "FleetId": null,
      "HostXRef": null,
      "Language": null,
      "LastUpdateDate": "0001-01-01T00:00:00",
      "ReqUser": null,
      "Status": null,
      "UpdatedUser": null
    },
    {
      "CustomerID": null,
      "DeptId": "180375",
      "DeptName": "testnewdept0215",
      "DeptNum": null,
      "FleetId": null,
      "HostXRef": null,
      "Language": null,
      "LastUpdateDate": "0001-01-01T00:00:00",
      "ReqUser": null,
      "Status": null,
      "UpdatedUser": null
    },
    {
      "CustomerID": null,
      "DeptId": "180386",
      "DeptName": "aamtest50",
      "DeptNum": null,
      "FleetId": null,
      "HostXRef": null,
      "Language": null,
      "LastUpdateDate": "0001-01-01T00:00:00",
      "ReqUser": null,
      "Status": null,
      "UpdatedUser": null
    },
    {
      "CustomerID": null,
      "DeptId": "180368",
      "DeptName": "managers",
      "DeptNum": null,
      "FleetId": null,
      "HostXRef": null,
      "Language": null,
      "LastUpdateDate": "0001-01-01T00:00:00",
      "ReqUser": null,
      "Status": null,
      "UpdatedUser": null
    },
    {
      "CustomerID": null,
      "DeptId": "180280",
      "DeptName": "2223FU",
      "DeptNum": null,
      "FleetId": null,
      "HostXRef": null,
      "Language": null,
      "LastUpdateDate": "0001-01-01T00:00:00",
      "ReqUser": null,
      "Status": null,
      "UpdatedUser": null
    },
    {
      "CustomerID": null,
      "DeptId": "180284",
      "DeptName": "DeptUCXAr",
      "DeptNum": null,
      "FleetId": null,
      "HostXRef": null,
      "Language": null,
      "LastUpdateDate": "0001-01-01T00:00:00",
      "ReqUser": null,
      "Status": null,
      "UpdatedUser": null
    },
    {
      "CustomerID": null,
      "DeptId": "180297",
      "DeptName": "testdept0204",
      "DeptNum": null,
      "FleetId": null,
      "HostXRef": null,
      "Language": null,
      "LastUpdateDate": "0001-01-01T00:00:00",
      "ReqUser": null,
      "Status": null,
      "UpdatedUser": null
    },
    {
      "CustomerID": null,
      "DeptId": "180421",
      "DeptName": "testdp0301",
      "DeptNum": null,
      "FleetId": null,
      "HostXRef": null,
      "Language": null,
      "LastUpdateDate": "0001-01-01T00:00:00",
      "ReqUser": null,
      "Status": null,
      "UpdatedUser": null
    }
  ];

  export default cardsOrderDepartments;